### ISSUE TITLE
npm global install fails on linux

### ISSUE THREAD

**Issue by michelluther** [ui5-community/generator-ui5-project#10]
Dear team,

I am failing to npm install the generator in version 3.0.1 fails with authorization error on linux during the postinstallation.

This is what I do:
`sudo npm install generator-easy-ui5 -g`

Maybe the sudo run as is not being propagated?

I have attached the result.
[installation_output.txt](https://github.com/ui5-community/generator-ui5-project/files/6467388/installation_output.txt)

Installation works fine with version 2.4.6.

Thanks a lot
Michel

**Comment by vobu** [comment]
jep, the log hints to some dir confusion caused by `sudo`. 
just do a `npm i -g yo generator-easy-ui5`
(note the `yo` also being installed globally as a peer dep)
hth, v.

**Comment by vobu** [comment]
(i closed this by accident, sorry. please reopen if necessary)

**Comment by michelluther** [comment]
Hi Volker,

thanks for looking into this.

It is the default behaviour for npm to install global packages into the folder `/usr/lib/node_modules`. Without sudo this will not work.

There are workarounds (like [this](https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md) one) for this, but by default, linux users will experience this, i believe. And so do i :-).

Cheers
Michel

**Comment by michelluther** [comment]
I can confirm that the issue is resolved by changing the default folder for global packages for npm.

So it works for me now. 

Cheers
Michel
