### ISSUE TITLE
Feature: FLP Plugin Project Type

### ISSUE THREAD

**Issue by ubheamar** [ui5-community/generator-ui5-project#11]
Hello Marius,

I was thinking to create a generator for the FLP plugin project. Can you suggest where should I add this generator  **generator-ui5-project** or **generator-ui5-library** or entirely create a new project in **UI5 Community**

I saw the main generator [generator-easy-ui5](https://github.com/SAP/generator-easy-ui5)  fetching repository from 
UI5 Community & showing list if we don't pass any options to the generator.

Let me know any other contribution required from my side I am happy to do that.

**Comment by IObert** [comment]
Hi Amar,

thanks for opening this issue. You are right, easy-ui5 pulls the templates from this GitHub org.

My first reaction would be that it's probably easiest to fork this project, remove files that you don't need and add the plugin-specific details.

CC: @petermuessig WDYT?

**Comment by petermuessig** [comment]
Hi @ubheamar ,

nice to see you here! 👍 

Regarding the FLP plugin: if it should be a standalone project which just creates the FLP plugin project, it makes sense IMO to have a separate generator. But if you intend to make this a flavour of a UI5 project - to add a FLP plugin there then it maybe belongs better to the ui5-project. 

@IObert : we should also discuss how to externalize the platform specific enablement you have in the ui5-project generator. This can be maybe useful for different generators as an addition. 

Best regards,
Peter

**Comment by IObert** [comment]
>  how to externalize the platform specific enablement

Yes, I was thinking along the same lines. But I'm not sure if we can do this. Then entire project is more or less just the platform specific enablement + the subgenerators for models etc. And some subgenerators (e.g. for views)  are even used for the main generator. So I'm not sure if it make much sense to split this project even further.

**Comment by ubheamar** [comment]
Thanks for the reply 👍  @IObert  & @petermuessig.

I think we already have sufficient generators for **generator-ui5-project**. it's better to not split more. Also for the FLPPlugin generator, There will be entirely different manifest.json structure & project structures, I thinking to fork this project build a standalone generator similar to  **generator-ui5-project**

Give me your comments so that I can start working on it.

Regards,
Amar Ubhe

**Comment by petermuessig** [comment]
One you are ready, let us know so that we can create a project for you

**Comment by ubheamar** [comment]
Hello @IObert & @petermuessig, 
I am ready with the project. can you create a project for me so that I can upload my code?
Regards,
Amar Ubhe

**Comment by IObert** [comment]
How do you want to name this project? And would you prefer an fresh project or should I create a fork of ui5-project (so that you could merge upstream changes every now and then)?

**Comment by ubheamar** [comment]
I think fresh project will be good. I have given the app name generator-ui5-flp-plugin.

**Comment by IObert** [comment]
Alright, I created a (for now) private repo for you to test. And I also assigned your the "write" access.

@petermuessig Is this ok or do you usually give "maintain" access out?

**Comment by IObert** [comment]
https://github.com/ui5-community/generator-ui5-flp-plugin

**Comment by petermuessig** [comment]
Hi @IObert , yes - we give "maintain" access unless there are some issues in future. I am a big fan of trust... 😄

**Comment by petermuessig** [comment]
You could finally close this issue, right? The new project has been created...

**Comment by ubheamar** [comment]
Hi @IObert , I have uploaded the code & tested it from my side as well. it's working fine with the easy-ui5 generator.
If any of you test & provide feedback that will be great.
I will close this issue.
Also, if I have to communicate with you guys in the future, should I create an issue for that new repository or set up a discussion tab?

**Comment by IObert** [comment]
I tested it and I'll provide feedback via issues in the new repo, ok?

Yes, I guess opening issues for other repos is a good approach.
