### ISSUE TITLE
"New view" generator doesn't work in existing UI5 projects

### ISSUE THREAD

**Issue by IObert** [ui5-community/generator-ui5-project#17]
## Steps to reproduce the problem:

1. Clone the sample repo <https://github.com/SAP/openui5-sample-app>
2. Run `yo easy-ui5 project newview` in there.

## What is the expected result?
That it prompts the right questions

## What happens instead?
Starts with the question "To which module do you want to add a view?"

## Any other information? (attach screenshot if possible)
Originally report in the [SAP Community](https://blogs.sap.com/2021/04/09/easy-ui5-3.0-from-community-contributions-to-community-plugins/comment-page-1/#comment-596031)

**Comment by octavonu** [comment]
HI,
I am encountering the same issue.

Thank you

yo easy-ui5 project newview
![image](https://user-images.githubusercontent.com/50553626/141845885-0249d025-2e9a-4255-adeb-b2fc7501e410.png)

**Comment by octavonu** [comment]
Hello @IObert ,

Thank you very much for your update. 

Now it is working as desired. 
One small glitch, the generator doesn't recognise itself...or?
  
The project was generated with Easy-UI5 for ts. What have I done wrong, I  cannot understand. 

VG 

![image](https://user-images.githubusercontent.com/50553626/142486186-4069c6a9-7c4b-4757-a7f2-d3e4c4d0901b.png)

**Comment by wridgeu** [comment]
Seems like this has something to do with the difference of content within the `.yo-rc.json` file. Which differentiates between the (technically) two used generators.

Typescript generator (https://github.com/ui5-community/generator-ui5-ts-app)
```json
{
  "generator-ui5-ts-app": {
    "application": "myapp",
    "namespace": "com.myorg",
    "framework": "OpenUI5",
    "frameworkVersion": "1.90.1",
    "author": "Some Name",
    "tstypes": "@openui5/ts-types-esm",
    "tstypesVersion": "1.90.1",
    "appId": "com.myorg.myapp",
    "appURI": "com/myorg/myapp",  
    "setupCompleted": true
  }
}
```

"Normal" generator (https://github.com/ui5-community/generator-ui5-project)
```json
{
  "generator-template-ui5-project": {
    "projectname": "ui5learning",
    "namespaceUI5": "com.myorg",
    "platform": "Static webserver",
    "viewtype": "XML",
    "ui5libs": "Content delivery network (OpenUI5)",
    "newdir": false,
    "codeassist": true,
    "namespaceURI": "com/myorg",
    "opa5pos": [
      "Main"
    ],
    "opa5Journeys": [
      "Main"
    ],
    "uimodules": [
      "uimodule"
    ],
    "setupCompleted": true
  }
}
```

The normal generator is looking for a few attributes (e.g. `viewtype`) and as it can't find any, it starts with the regular prompting as can be seen here https://github.com/ui5-community/generator-ui5-project/blob/main/generators/newview/index.js#L62

Looks to me like an adjustment has to be made within the [ts-generator](https://github.com/ui5-community/generator-ui5-ts-app) except @IObert would prefer taking this different config into account within the newview subgenerator?

**Comment by IObert** [comment]
I would say this behavior is intended (at least for now). If we'd support this, there had to be some TS logic in `ui5-project` as well to make sure to generate TS code when used in the other context. And this would basically merge both plugins in one - which would violate the original design choice that @petermuessig  and I made.

But that doesn't mean this decision is set in stone.
