### ISSUE TITLE
Easy-UI5 doesn't generated an FlpSandbox since using new @sap/ux-ui5-tooling

### ISSUE THREAD

**Issue by IObert** [ui5-community/generator-ui5-project#19]
## Easy-Ui5 version:

Most recent aka 3.0.3

## Steps to reproduce the problem:

Described here: <https://answers.sap.com/questions/13530042/tutrial-creating-fiori-lauinchpad-app-error.html?childToView=13531170>

## What is the expected result?

The project should include a flpSandbox that displays the web app.

## What happens instead?

The flpSandbox is not in the `webapp` folder but in `webapp/test`. But then when using this path, the app won't show properly.

![Screenshot 2021-11-23 at 11 02 10](https://user-images.githubusercontent.com/1873245/143004638-5c322b09-0da2-4bbd-b11d-a3c7dae70f4a.png)

**Comment by IObert** [comment]
@vobu Do you think this is something we can fix in this project, or is this something that needs to be fixed in @sap/ux-ui5-tooling ?

**Comment by vobu** [comment]
hm, let me take a look. will report back.
