### ISSUE TITLE
chore(deps): handle changes dep install and logging for yeoman^5

### ISSUE THREAD

**Issue by vobu** [ui5-community/generator-ui5-project#23]
Once this generator switches to yeoman^5, the introduced changes in that major version need to be reflected here (as described in https://github.com/SAP/generator-easy-ui5/pull/82):
- manage dependency installs 
- handle changed logging

**Comment by IObert** [comment]
On it :)

**Comment by IObert** [comment]
So, I did some deeper testing and there are a few blocker that come from updating the dependencies of this project. So this is a larger task for now. Here are the repos that need to be updated first, before the dep install issue itself can be resolved:

- [ ] chalk              ^4.1.2  →  ^5.0.0     (Must use import to load ES Module)
- [ ] valid-filename     ^3.1.0  →  ^4.0.0    (Must use import to load ES Module)
- [ ] yeoman-generator  ^4.13.0  →  ^5.4.2    (Comes with failing test cases)
- [ ] execa              ^5.1.1  →  ^6.0.0   (Must use import to load ES Module)

I'll try to find some time for this but I can't promise anything so far.
