### ISSUE TITLE
Providing some documentation on how to contribute

### ISSUE THREAD

**Issue by lboehm** [ui5-community/generator-ui5-project#25]
Hi @IObert,

I think it would help if there were any documentation for people who want to contribute to this generator. I was quite struggling to get started, especially debugging wasn't easy. I didn't get it running at the weekend, because I found out that the problem can't be solved in this repo, so I didn't dig deeper on how to debug. Probably it's not complicated if you know what to do. But it would help people when they want to contribute.

What do you think? Could you or someone else provide some information. 

BR,
Lukas

**Comment by IObert** [comment]
I understand the problem and I like the idea. Let me see if I find some time next week or so :)

**Comment by IObert** [comment]
I added a small section here <https://github.com/ui5-community/generator-ui5-project#debugging-the-generator>
Let me know if you like it / it makes sense :)

**Comment by lboehm** [comment]
It makes perfect sense. Thanks a lot!
