### ISSUE TITLE
eslint always looks for "xml", even if oConfig.viewtype=="JSON"

### ISSUE THREAD

**Issue by nicogeburek** [ui5-community/generator-ui5-project#33]
## Easy-Ui5 version:

Node.js: v16.9.1
yeoman-environment: 3.9.1
generator-easy-ui5: 3.2.1
home: /Users/i533499/Documents/coding/generator-easy-ui5
pluginsHome: /Users/i533499/Documents/coding/generator-easy-ui5/plugin-generators
Available generators:
  - generator-ui5-project: 0.1.1

## Steps to reproduce the problem:

1. Run `yo easy-ui5 project`
1. Create a new `app` 
1. Select `JSON` as view type

## What is the expected result?

`lint-fix` should run smoothly after installation.

## What happens instead?

<img width="683" alt="Screenshot 2022-02-11 at 10 54 49" src="https://user-images.githubusercontent.com/65965098/153571041-5b80389e-c3bf-4fe4-8c14-a7f1ecd3176a.png">

This is related to @lboehm's [PR a few weeks ago](https://github.com/ui5-community/generator-ui5-project/pull/28/files#diff-fb3c51194730e282793310751066bf26defbbee94fc60924bbde9d954f646e6fR162). `eslint` specifically looks for `xml`. I guess we should look for a different pattern or make this dependent on `oConfig.viewtype`.

**Comment by vobu** [comment]
just .02€: is it really worth any effort to support `json` view types? they should go away asap anyway 😸

**Comment by nicogeburek** [comment]
Good point, I won't be the one making the call here but I don't disagree 😉

**Comment by wridgeu** [comment]
> just .02€: is it really worth any effort to support `json` view types? they should go away asap anyway 😸

I agree. With all the best practices / guidance out there what one _should_ use or what would be best. And the generator trying to be part of this guiding force i.e. https://github.com/ui5-community/generator-ui5-project/issues/21.  I don't think supporting every possible use-case, especially going against these "best practices", is a good thing. Could also be 'annoying' in regards to maintainability in the long run (maybe, possibly ... ^^).

On the other hand ... it's *possible* to use `json` views and therefore part of UI5 ... so ... yeah, my .0**1**€ 😅

**Comment by petermuessig** [comment]
The default should be the `XMLView`s IMO. 

But the error of lint can also be supressed by adding a command line option:
https://eslint.org/docs/user-guide/command-line-interface#--no-error-on-unmatched-pattern

`--no-error-on-unmatched-pattern`

This is what I would suggest to fix immediately to add this parameter to the eslint execution and as a second step, the default should become `XMLView`s  and `JSONView`s can be seen as optional.
