### ISSUE TITLE
Allow usage of Promises when using code assist

### ISSUE THREAD

**Issue by lboehm** [ui5-community/generator-ui5-project#39]
Hi!

When generating a project with code assist, the following error is shown, when you're using promises:

*any 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.ts(2585)*

![image](https://user-images.githubusercontent.com/6696988/158009963-7ba66219-72c8-44af-83fb-506005fbe44d.png)

I think, it should be easily possible to use Promises, especially after IE11 support is dropped. To solve this issue the `tsconfig.json` has to be changed:

```json
{
    "compilerOptions": {
        "module": "none",
        "noEmit": true,
        "checkJs": true,
        "allowJs": true,
        "types": ["@sapui5/ts-types"],
        "lib": ["es2015"]                    <<< new
    }
}
```

**Important:** The `eslint.rc` file should have the following config, otherwise we will receive another error:

![image](https://user-images.githubusercontent.com/6696988/158010513-5e11bd7f-635d-4248-9d53-e35204a79ea4.png)

```json
{
    "env": {
        "es6": true
    },
```

This PR does not contain the necessary change in the `eslint.rc`, because this change comes with the PR #31. 

So if you like you can wait with merging this one, until #31 is resolved. Or you merge this one now, because the devs will receive just a different error message than they currently do. So no big difference.

BR,
Lukas

**Comment by petermuessig** [comment]
Fixed with #40
