### ISSUE TITLE
Duplicate entries in `.eslintrc` for project scaffolding

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/generator-ui5-project#47]
Hey there, 👋

I've noticed that the `.eslintrc` file will always have duplicate entries (see img below) when agreeing on adding the "code assist libraries" during the project scaffolding (cmd: `yo easy-ui5 project`).

![image](https://user-images.githubusercontent.com/14982812/172191558-3b3c7b56-7c1d-4292-ae30-5a27efba9b27.png)

This is because these options are being set here:

https://github.com/ui5-community/generator-ui5-project/blob/126a3207bc73cc5a8049b344059e2c96310e828e/generators/app/index.js#L129-L132

 even though they already exist in the base `.eslintrc` file for this type of generator:

https://github.com/ui5-community/generator-ui5-project/blob/126a3207bc73cc5a8049b344059e2c96310e828e/generators/app/templates/_.eslintrc#L81-L82

Would it make sense to remove these additions (plugins & extends) in the `index.js`? I think using JSDoc is viable even without the type-hinting from the `tsconfig.json`.

**Comment by vobu** [comment]
yeah, clean up here definitely makes sense - in favor of the explicit `_.eslintrc`, since its easier to maintain declarations in a file rather than in src code. Mind giving it a shot aka PR 😺?

**Comment by wridgeu** [comment]
@vobu great, thanks for the feedback :) created one with these small adjustments, didn't request a reviewer yet. If you wouldn't mind you can go ahead ^^
