### ISSUE TITLE
App.controller.js has wrong namespace

### ISSUE THREAD

**Issue by MichaelFlucher** [ui5-community/generator-ui5-project#55]
## Easy-Ui5 version:
3.5.0

> Run `yo easy-ui5 --plugins` to print all relevant version strings

Node.js: v16.13.0
yeoman-environment: 3.10.0
generator-easy-ui5: 3.5.0
Available generators:
  - ui5-project: 0.2.0

## OS/version:
Windows 10 Enterprise 21H2 19044.1826

## Steps to reproduce the problem:

`yo easy-ui5 project app`
```
? How do you want to name this project? generatorBug
? Which namespace do you want to use? test
? Do you want to enable the SAP Fiori elements flexible programming model? No
? On which platform would you like to host the application? SAP Launchpad service
? Which view type do you want to use? XML
? Where should your UI5 libs be served from? Content delivery network (SAPUI5)
? Would you like to create a new directory for the project? No
? Would you like to add JavaScript code assist libraries to the project? No  
? Would you like to initialize a local git repository for the project? No
? What name should be displayed on the Fiori Launchpad tile? App1
```
- after npm install finished, open `uimodule\webapp\controller\App.controller.js` 
- in line 9 the namespace contains `controll.controller`

## What is the expected result?
`return BaseController.extend("test.generatorBug.controller.App", {`

## What happens instead?
`return BaseController.extend("test.generatorBug.controller.controller.App", {`

**Comment by wridgeu** [comment]
Hey there,

nice find. :) 

Looks like it'll have to be changed in https://github.com/SAP/open-ux-tools/blob/cada427943dccee6382e1ce0e7ec8ba210996493/packages/fiori-freestyle-writer/templates/basic/add/webapp/controller/App.controller.js

@tobiasqueck Is there a certain way to go about handling these cross repository things like a "requirement" let's say, to have this issue opened over at the `open-ux-tools` as well or will a straight PR there with a link to this issue be enough?
