### ISSUE TITLE
ajax and  xhr are not available in

### ISSUE THREAD

**Issue by horsemanjackyliu** [ui5-community/generator-ui5-project#63]
## Easy-Ui5 version:

> Run `yo easy-ui5 --plugins` to print all relevant version strings

Node.js: v14.19.3
yeoman-environment: 3.9.1
generator-easy-ui5: 3.3.0
home: C:\Develop\nodejs\node_global\node_modules\generator-easy-ui5
pluginsHome: C:\Develop\nodejs\node_global\node_modules\generator-easy-ui5\plugin-generators

Available generators:
  - generator-ui5-project: 0.2.1
  - generator-ui5-ts-app: 1.0.1

## Steps to reproduce the problem:

1. Step 1
use yo easy-ui5 project   to generate a ui5 project.
2. Step 2
Change MainView.controller.js
3. Step 3
add the following code in onInit funnction:
 let xhr = new XMLHttpRequest();

the error is "Cannot find name 'XMLHttpRequest'.ts(2304)"

$.ajax also can not be used .

## What is the expected result?

In the generated project XHR and ajax can be used .

**Comment by nicoschoenteich** [comment]
Hi @horsemanjackyliu,
I just tested it myself and this works:
```js
sap.ui.define(
    ["./BaseController"],
    /**
     * @param {typeof sap.ui.core.mvc.Controller} Controller
     */
    function (Controller) {
        "use strict";

        return Controller.extend("com.myorg.myUI5App.controller.MainView", {
            onInit: function () {
                console.log(jQuery.ajax())
                console.log(new XMLHttpRequest())
            },
        });
    }
);
```

<img width="644" alt="Screenshot 2022-12-06 at 17 12 48" src="https://user-images.githubusercontent.com/65965098/205964302-41594cfe-41df-4101-87b6-91fb6eae0040.png">

Can you try `jQuery.ajax()` ?

Best, Nico

**Comment by nicoschoenteich** [comment]
Hi @wridgeu,
Thanks, appreciate it! Makes total sense to skip the whole global thing - thanks for pointing it out.

@horsemanjackyliu, do you experience runtime errors as well? Or is this only regarding type checking during development? 

Best, Nico

**Comment by wridgeu** [comment]
Hey @nicoschoenteich,

I think this issue can be closed. Dont want to be too presumptuous here but it doesn't seem to have been an actual _error_ and I think it was mostly for his [blog post](https://blogs.sap.com/2022/12/08/download-and-view-pdf-document-from-btp-document-management-service/), which seems to have worked out fine. :)

BR, Marco
