### ISSUE TITLE
Error with ui5-project generator

### ISSUE THREAD

**Issue by Finbar-Callaghan** [ui5-community/generator-ui5-project#69]
## Easy-Ui5 version: 3.6.2

> Run `yo easy-ui5 --plugins` to print all relevant version strings
Node.js: v16.20.0
yeoman-environment: 3.15.1
generator-easy-ui5: 3.2.0
home: /Users/finbarcallaghan/Projects/SAP/UI5/Yogenerated/node_modules/generator-easy-ui5
pluginsHome: /Users/finbarcallaghan/Projects/SAP/UI5/Yogenerated/node_modules/generator-easy-ui5/plugin-generators

Available generators:
  - generator-ui5-app: 1.1.0
  - generator-ui5-project: 0.3.1
  - generator-ui5-ts-app: 1.1.0

## OS/version:
Mac OS Ventura 13.4.1

## Browser/version (+device/version):
Chrome Version 115.0.5790.170 
## Steps to reproduce the problem:

1. "yo easy-ui5 project"
2. "app"
3. Step 3

## What is the expected result?
progresses to the new step

## What happens instead?
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sap-ux/ui5-config' imported from /Users/finbarcallaghan/Projects/SAP/UI5/Yogenerated/node_modules/generator-easy-ui5/plugin-generators/generator-ui5-project/generators/enablefpm/index.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sap-ux/ui5-config' imported from /Users/finbarcallaghan/Projects/SAP/UI5/Yogenerated/node_modules/generator-easy-ui5/plugin-generators/generator-ui5-project/generators/enablefpm/index.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)

## Any other information? (attach screenshot if possible)
Hello,
I’m hoping you can help me with the following error, as you can see from below I’m running version 16.20 of node and yo doctor hasn’t picked up anything. It appears that the Project generator does not work, however the odd thing is that Typescript generator does works. In addition the Project generator did work for me back on June 30 from the perspective of version control!

<img width="386" alt="image" src="https://github.com/ui5-community/generator-ui5-project/assets/141810374/01767541-682c-43a5-8f35-a84911805a94">

With the following directory reference
![image](https://github.com/ui5-community/generator-ui5-project/assets/141810374/2c14f62e-7e99-40b1-9727-6f6f63f48017)

The list of modules that are missing are listed as follows;
“@sap-ux/fe-fpm-writer” error
Within etc./generators/enablefpm/index.js & etc./generators/newfpmpage/index.js
“@sap-ux/ui5-application-writer” error
Within etc./generators/newwebapp/index.js
“object-assign-deep” error
Within etc./helpers/fileaccess.js
“valid-filename” error
![image](https://github.com/ui5-community/generator-ui5-project/assets/141810374/0ab9c71a-ec0c-4021-a10a-8c981a724c82)

“@sap-ux/ui5-config” & “@sap-ux/odata-service-writer”

My list of plugins are as follows
<img width="482" alt="image" src="https://github.com/ui5-community/generator-ui5-project/assets/141810374/2c8ebfe9-6f13-4f16-8416-f0bd05825b5d">

I did wonder is this anything to do with legacy generators, as I get the following error when doing a forceUpdate
![image](https://github.com/ui5-community/generator-ui5-project/assets/141810374/06b25dd4-1d9c-40ab-bc97-17d4d1739115)
When I list the additional modules I get the same error
<img width="452" alt="image" src="https://github.com/ui5-community/generator-ui5-project/assets/141810374/50ffbc12-1a11-42d0-9e54-5b9a0c0e7933">
Thanking you in advance,
Finbar

**Comment by petermuessig** [comment]
Hi @Finbar-Callaghan ,

seems that your `generator-easy-ui5` version is not up-to-date (yours: `3.2.0`, mine: `3.6.2`):
<img width="360" alt="image" src="https://github.com/ui5-community/generator-ui5-project/assets/1589419/4e7e15c1-0fd9-4ed8-9631-635206bffc2e">

Can you please update your Easy UI5 generator with `npm i -g generator-easy-ui5`? Then it should work for you...

**Comment by Finbar-Callaghan** [comment]
Hello Sir,
Thank you for thanking the time to respond to my request, greatly appreciated @petermuessig , it seems to have worked like a dream after a bit of regeneration. I will play with it later this evening...
![image](https://github.com/ui5-community/generator-ui5-project/assets/141810374/080f44be-4da9-404b-9d0d-6ee1941f33b1)
Have a good day, Vielen Dank.
Finbar
