### ISSUE TITLE
Remove JS View from template(s)

### ISSUE THREAD

**Issue by tobiashofmann** [ui5-community/generator-ui5-project#74]
# easy-ui5 version

easy-ui5 3.8.1

# Steps to reproduce

yo easy-ui5 project

# Observed behavior

Wizard asks for view type and gives as option: XML and JS 

<img width="562" alt="image" src="https://github.com/ui5-community/generator-ui5-project/assets/2013590/4c2dd577-51d8-4469-a852-b66084d30dfb">

# Expected result

Is it possible to remove the view type JS? Seems that from the other templates this view type is already removed (yo easy-ui5 -> app -> does not ask and uses XML). Giving the users the option to use JS as view type will make it hard to find examples in the [UI5 SDK docu](https://sdk.openui5.org/topic/91f27e3e6f4d1014b6dd926db0e91070) 

"Therefore, we concentrate on XML views and only provide examples for XML views throughout this documentation."

**Comment by nicoschoenteich** [comment]
Hi @tobiashofmann,
the JS ("typed") view is still technically supported: https://ui5.sap.com/#/topic/e6bb33d076dc4f23be50c082c271b9f0
You are right though - it doesn't get much love in the docs.
I am currently working on a complete rewrite of for this generator (stay tuned for a session about this at UI5con 2024), and JS views will not be part of that.
Best, Nico
