### ISSUE TITLE
Error - [ERR_UNSUPPORTED_ESM_URL_SCHEME]

### ISSUE THREAD

**Issue by Aoki10** [ui5-community/generator-ui5-project#76]
Hi im trying to recreate what was presented on UI5CON in Easy UI5 project generator 2.0 by Nico Schoenteich and i ve got an issue.
I ve clone his repository https://github.com/nicoschoenteich/generator-ui5-project and went through the wizard in console but the program keeps falling on this. Do you have any solution ?

![image](https://github.com/ui5-community/generator-ui5-project/assets/103956898/12fd9064-2905-4394-891a-650f2fe4a221)

**Comment by nicoschoenteich** [comment]
Yep, still working on the Windows compatibility - on it!

**Comment by nicoschoenteich** [comment]
This is now fixed. Also, the PR https://github.com/ui5-community/generator-ui5-project/pull/75 is now merged.
